""" 
This one is like constants except about game rules
always import as gb
"""

PLAYER_SPEED = 4

PLAYER_BULLET_SPEED = 10
ENEMY_BULLET_SPEED = 6

DEFAULT_BULLET_DAMAGE = 1

DODGE_ROLL_DODGE_TIME = 25
DODGE_ROLL_COOLDOWN_TIME = 40
DODGE_ROLL_SPEED_FACTOR = 1.7
DODGE_ROLL_SLOW_FACTOR = 0.3

SINGLE_SHOT_COOLDOWN = 15
SAWED_OFF_SHOT_COOLDOWN = 45
CIRCLE_SHOT_COOLDOWN = 30

ENEMY_KNOCKBACK = 30
KNOCKBACK_DAMAGE = 1

PLAYER_HEALTH = 6
ENEMY_HEALTH = 10

ENEMY_MOVE_SPEED = 1

ENEMY_ATTACK_CHANCE = 90000

CIRCLE_SHOT_RANGE = 20
SAWED_OFF_RANGE = 15
SINGLE_SHOT_RANGE = 80
SNIPER_SHOT_COOLDOWN = 70
SNIPER_SHOT_SPEED = 30
SNIPER_SHOT_DAMAGE = 8

GATLING_GUN_COOLDOWN = 2
BURST_FIRE_COOLDOWN = 25