""" 
This one is like constants except about game rules
always import as gb
"""

""" Move Speeds """
PLAYER_SPEED = 4
ENEMY_MOVE_SPEED = 2.5
CHASER_MOVE_SPEED = 6

""" Bullet Speeds """
PLAYER_BULLET_SPEED = 10
ENEMY_BULLET_SPEED = 6
SNIPER_SHOT_SPEED = 30

""" Health Values """
PLAYER_HEALTH = 6
ENEMY_HEALTH = 10


""" Damage Values """
DEFAULT_BULLET_DAMAGE = 1
SNIPER_SHOT_DAMAGE = 8
KNOCKBACK_DAMAGE = 1


""" Ranges """
CIRCLE_SHOT_RANGE = 20
SAWED_OFF_RANGE = 15
SINGLE_SHOT_RANGE = 80


""" Cooldowns """
SINGLE_SHOT_COOLDOWN = 15
SAWED_OFF_SHOT_COOLDOWN = 45
CIRCLE_SHOT_COOLDOWN = 30
SNIPER_SHOT_COOLDOWN = 70
GATLING_GUN_COOLDOWN = 2
BURST_FIRE_COOLDOWN = 25


""" Dodge Roll """
DODGE_ROLL_DODGE_TIME = 25
DODGE_ROLL_COOLDOWN_TIME = 40
DODGE_ROLL_SPEED_FACTOR = 1.7
DODGE_ROLL_SLOW_FACTOR = 0.3


""" Misc """
ENEMY_KNOCKBACK = 30
ENEMY_ATTACK_CHANCE = 90000
